// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ounpfnhnkrmcpgkhivqs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91bnBmbmhua3JtY3Bna2hpdnFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExNTQ5NTAsImV4cCI6MjA2NjczMDk1MH0.JRpcJfAjZ17pt5yGRTvJn39DoLwI8_kjxKfS6uKXuuc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});